### PR TITLE
Electriclizard solution2

### PR DESCRIPTION
**Pull request by electriclizard**
Hi again 👋!
I've tested some approaches like threading and multiprocessing with queues and got that exchange between processes is a real expensive operation. Now it works in 1 cpu process and uses 10.7 gb of gpu memory on a full load, so it may be ran on a smaller instance, like g4dn.xlarge, because this solution doesen't need so much cpu cores.
I've tested it on my 3060 gpu and got 560 rps on it with a wrk bench tool, also we can play with a timeout parameter in configs/app_config.yaml, changing a delay and waiting for a batch.

### CODE REVIEW

**Review by rsolovev — COMMENTED** [review]
Hey @electriclizard, here are our test [results](https://grafana.sm.inca.digital/dashboard/snapshot/JmBImT9HVnB4zzqbign9wtzvTaZVCqBR?orgId=0) for this iteration, thank you for this marvellous solution!

**Comment by electriclizard** [comment]
Hello @rsolovev, i've made some changes and got some perfomance growth on local tests.

**Review by rsolovev — COMMENTED** [review]
Hi! We can also see a noticeable increase in throughput on our [tests](https://grafana.sm.inca.digital/dashboard/snapshot/5x4fr0VXvR9xYU3JkBe01ouppwKMv9gJ), thank you!

**Review by rsolovev — COMMENTED** [review]
@electriclizard thank you, here are the [results](https://grafana.sm.inca.digital/dashboard/snapshot/6c9CAyjSd2Lssi8SW7CyawadLVs0Y5mu) for the latest commit from this branch

**Comment by electriclizard** [comment]
Hi @rsolovev, i've tried an onnx runtime for the model inference and got some perfomance growth. I also know about model optimization for transformers from this [link](https://huggingface.co/docs/optimum/v1.2.1/en/onnxruntime/modeling_ort). This solution has no model optimization, i can turn it on if it's allowed, but according to readme model optimization is not allowed, am i right?

**Comment by rsolovev** [comment]
@electriclizard after some discussion, we agreed on the following: "As long as the model optimization is done in the runtime, we won't disregard that solution right away", and `Optimum Inference with ONNX Runtime` seems to fit in the allowed category

**Review by rsolovev — COMMENTED** [review]
@electriclizard fyi -- ran the latest commit, there are some onnx errors -- [log](https://github.com/1712n/infra-challenge/files/11663749/inca-smc-mlops-challenge-solution-95477b5bb-f25nw.log)

**Comment by electriclizard** [comment]
@rsolovev i've fixed the issue and add graph optimizations

**Review by rsolovev — COMMENTED** [review]
@electriclizard, onnx errors on launch still -- 
[inca-smc-mlops-challenge-solution-65ff444889-9w8bj.log](https://github.com/1712n/infra-challenge/files/11675392/inca-smc-mlops-challenge-solution-65ff444889-9w8bj.log)

**Comment by electriclizard** [comment]
Thank you for a try and for a log!
 I've built and ran this commit for several times and haven't met this error, so i'll try to reproduce it and make a fix

**Comment by electriclizard** [comment]
@rsolovev i've made a hot fix, may be it colud help, but still can't reproduce it locally
image

**Comment by electriclizard** [comment]
> @electriclizard still the same error, and I cant seem to understand why too -- I'll briefly look into that

i will now fix the base docker version

**Review by rsolovev — COMMENTED** [review]
@electriclizard thanks, now everything is fine, here are the [results](https://grafana.sm.inca.digital/dashboard/snapshot/wp6gwRK5OZZCfcGR68Absn4D2HK7lCSf)

**Comment by electriclizard** [comment]
Hi @rsolovev, i've made a new solution, metrics raises, but i am still working on it, can you please explain me how can i correctly deploy an application using docker-compose?
image

**Review by darknessest — APPROVED** [review]

**Review by rsolovev — APPROVED** [review]

**Comment by darknessest** [comment]
Congratulations, @electriclizard! 
You submitted the most performant and quite ingenious solution and you showed a great depth of knowledge of MLOps

**Pull request merged**
